# Generated by Django 5.1.5 on 2026-01-30 15:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان خبر')),
                ('body', models.TextField(verbose_name='متن خبر')),
                ('category', models.CharField(choices=[('Technology', 'فناوری'), ('Sports', 'ورزشی'), ('Health', 'سلامتی'), ('Economics', 'اقتصادی'), ('Politics', 'سیاسی')], max_length=20, verbose_name='دسته\u200cبندی')),
                ('view_counter', models.IntegerField(default=0, verbose_name='تعداد بازدید')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'خبر',
                'verbose_name_plural': 'اخبار',
                'ordering': ['-view_counter'],
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('favorite_categories', models.JSONField(default=list, verbose_name='دسته\u200cهای مورد علاقه')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
