# Generated by Django 5.1.5 on 2026-01-30 16:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_userprofile_unique_user_profile'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='userprofile',
            name='unique_user_profile',
        ),
    ]
